# Generated by Django 4.1.4 on 2023-07-13 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('experiments', '0013_alter_experiment_initiator'),
        ('measurements', '0003_delete_cta_delete_monomer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_id', to='experiments.company'),
        ),
    ]
