# Generated by Django 4.1.4 on 2023-07-13 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('experiments', '0013_alter_experiment_initiator'),
        ('measurements', '0004_alter_device_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='experiments.company'),
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=127)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companyid', to='experiments.company')),
            ],
            options={
                'verbose_name': 'Machine',
                'verbose_name_plural': 'Machines',
            },
        ),
    ]
