# Generated by Django 4.1.4 on 2023-07-13 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0005_alter_device_company_machine'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Machine',
        ),
    ]
