# Generated by Django 4.0.6 on 2023-07-17 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('experiments', '0013_alter_experiment_initiator'),
        ('measurements', '0006_delete_machine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_id', to='experiments.company'),
        ),
    ]
