# Generated by Django 4.1.4 on 2023-08-09 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('experiments', '0025_alter_experiment_reagent_experiment_and_more'),
        ('measurements', '0007_alter_device_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='measurements.device'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='experiment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='getMeasurement', to='experiments.experiment'),
        ),
    ]
