# Generated by Django 4.1.4 on 2023-08-24 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0008_alter_measurement_device_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='measurement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurement', to='measurements.measurement'),
        ),
    ]
