# Generated by Django 4.1.4 on 2023-09-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0009_alter_data_measurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='d',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='mn',
            field=models.FloatField(null=True),
        ),
    ]
