# Generated by Django 4.1.4 on 2023-06-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemicals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name',
            name='abbreviation',
            field=models.CharField(max_length=511),
        ),
        migrations.AlterField(
            model_name='name',
            name='common_name',
            field=models.CharField(max_length=511),
        ),
        migrations.AlterField(
            model_name='name',
            name='iupac',
            field=models.CharField(max_length=511),
        ),
    ]
